rootProject.name = 'integrate-boot'

include('bom')
include('module:integrate-boot-base')
include('module:integrate-boot-data')
include('module:integrate-boot-jackson')
include('module:integrate-boot-logging')
include('module:integrate-boot-cache')
include('module:integrate-boot-redis')
include('module:integrate-boot-authentication')
include('module:integrate-boot-resource-server')
include('module:integrate-boot-starter')
include('test:integrate-boot-test')

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.aliyun.com/repository/public' }
    }
}
