plugins {
    id 'java-library'
}

apply from: "$rootDir/gradle/publishing.gradle"

dependencies {
    api platform(project(':bom'))
    api project(':module:integrate-boot-base')

    api(libs.spring.boot.autoconfigure)
    api(libs.spring.boot.starter.web) {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
    api(libs.xxl.job.core)

    annotationProcessor(libs.spring.boot.configuration.processor)

    testImplementation(libs.spring.boot.starter.test)
}
